# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

_api:
    resource: "@AdrienBraultApiBundle/Resources/config/routing/routing.yml"
